export const fakeTasks = [
  {
    id: "1",
    title: "Submit Q1 Marketing Report",
    description: "Prepare and submit quarterly marketing performance report",
    dueDate: "2026-02-15",
    assignee: "Sarah Manager",
    priority: "HIGH",
    category: "Reports",
    status: "Pending",
  },
  {
    id: "2",
    title: "Team Meeting - Budget Review",
    description: "Attend team meeting to discuss Q2 budget allocation",
    dueDate: "2026-02-16",
    assignee: "John Director",
    priority: "MEDIUM",
    category: "Meetings",
    status: "Pending",
  },
  {
    id: "3",
    title: "Client Presentation Prep",
    description: "Prepare presentation slides for upcoming client meeting",
    dueDate: "2026-02-18",
    assignee: "Sarah Manager",
    priority: "HIGH",
    category: "Presentations",
    status: "In Progress",
  },
  {
    id: "4",
    title: "Update Marketing Strategy",
    description: "Review and update marketing strategy for Q2",
    dueDate: "2026-02-20",
    assignee: "Marketing Team",
    priority: "MEDIUM",
    category: "Strategy",
    status: "In Progress",
  },
  {
    id: "5",
    title: "Social Media Content Calendar",
    description: "Create content calendar for March 2026",
    dueDate: "2026-02-22",
    assignee: "Sarah Manager",
    priority: "LOW",
    category: "Content",
    status: "In Progress",
  },
];
